# Generated by Django 6.0 on 2025-12-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='temp', max_length=100),
        ),
    ]
